config/routes.rb
Rails.application.routes.draw do
  
  get 'monologs/index'

  get 'monologs/show'

  get 'monologs/edit'

  get 'monologs/new'

  get 'cover_images/index'

  get 'cover_images/show'

  get 'cover_images/profile'

  # get 'messages/user/:id' =>'messages#user'
  
  # get 'messages/new' => 'messages#new'
  
  # post 'messages' => 'messages#create'
  # delete 'messages' => 'messages#destroy'
  
resources :profiles
resources :messages do 
  collection do
    get 'profile/:id' => 'messages#profile'
  end
end

resources :cover_images do 
  collection do
    get 'profile/:id' => 'cover_images#profile'
  end
end
  devise_for :users
  get 'pages/top'
  root 'pages#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 post 'relations/create' => 'relations#create'
 post 'relations/destroy' => 'relations#destroy_ajax'
 delete 'relations/:id' => 'relation#destroy'
 
 resources :monologs
end

app/models/message.rb
class Message < ApplicationRecord
    default_scope ->{order('created_at DESC')}
        belongs_to :from, class_name: 'Profile', :foreign_key => 'from_id'
        belongs_to :to, class_name: 'Profile', :foreign_key => 'to_id'
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action:set_request_from
  def index

  end
  def profile
    me =  current_user.profile.id
    who = params[:id]
    @whoProfile = Profile.find(who)
    @relation = Relation.where('profile_id':me,'target_profile_id':who)
    if @whoProfile.check_relation_status(me) != 'matching'
      redirect_to profiles_path
    end
    @messages = Message.where(from_id: me, to_id: who).or(Message.where(from_id: who, to_id: me)).page(params[:page]).per(5)
  
    # from_id = me and to_id = who
    # or
    # from_id = who and to_id = me    
    @message = Message.new
  end
  def new
    
  end
  
  def create
    @message = Message.new(message_params)

    if @message.save
      redirect_to :action => "profile", :id => @message.to_id
    else
    
    end     
  end
  def destroy
      @message = Message.find(params[:id])
      @message.destroy
     redirect_to :action => "profile", :id => @message.to_id
  end
  private
  def message_params
    params.require(:message).permit(:from_id,:to_id,:body)
  end 
  
  def set_request_from
    if session[:request_from]
      @request_from = session[:request_from]
    end
    # 現在のURLを保存しておく
    session[:request_from] = request.original_url
  end  
  def return_back
    if request.referer
      redirect_to :back and return true
    elsif @request_from
      redirect_to @request_from and return true
    end
  end  
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<div class="row">
<div class="col-md-3" id="side-col">
        <%= render partial: 'layouts/sidebar' %>
</div>
<div class="col-md-9" id="main-col">
    <div id="message-wall">
        <ul>
        <% @messages.each do |message|%>
            <li><%= message.body%></li>
        <% end %>            
        </ul>

    </div>
    <div class="row">
    <%= form_with model: @message,url:{controller: :messages,action: :create}, local: true do |form| %>
     
      <%= form.hidden_field :from_id,value: current_user.profile.id %>
      <%= form.hidden_field :to_id,value: params[:id]%>
        <div class="form-group">
        <%= form.label :body,"メッセージ送信" %><br>
        <%= form.text_area :body, class: "form-control" %>
        </div>       
         <%= form.submit class: "btn btn-default" %>
    <% end %>        
    </div>
</div>
</div>

app/views/messages/profile.html.erb
<div class="row">
<div class="col-md-3" id="side-col">
        <%= render partial: 'layouts/sidebar3' %>
</div>
<div class="col-md-9" id="main-col">
    <header id="message-header" class="clearfix">
        <%= link_to profiles_path,:class => 'go-index' do %>
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <% end %>
        <div class="who-info clearfix">
            <div class="who-image">
                
               <% if  @whoProfile.echo_user_icon %>
                <%= image_tag @whoProfile.echo_user_icon.url(:square),:width =>80,:height=>80%>
                <% else %>
                <img src=" https://dummyimage.com/60x60/cccccc/777.png">
                <% end %>                 
                
             
        </div>
         <h2 class="who-name">
            <%= @whoProfile.display_name %>
            <small class="last-sign-in">
              最終ログイン
                <time datetime="">
                    <%= time_ago_in_words(@whoProfile.user.last_sign_in_at)+"前" %> 
                </time>
            </small>         
       
         </h2>
        </div>
    </header>
    <div id="message-wall">
        <ul>
        <% @messages.each do |message|%>
            <% speaker = message.from_id == current_user.profile.id ? 'you' : 'who' %>
            <li class="message-item <%= speaker %> clearfix">
                <% if speaker == 'who' %>
                <div class="message-body">
                      <%= message.body%>
                      <div class="message-meta">
                      <%= time_ago_in_words(message.created_at)+"前" %> 
                      </div>                      
                </div>
                <% end %>
                
                
                <div class="message-footer">
                    <div class="profile-icon">
                 
                        
                        <% if  message.from.echo_user_icon %>
                        <%= image_tag message.from.echo_user_icon.url(:square),:width =>40,:height=>40%>
                        <% else %>
                        <img src=" https://dummyimage.com/60x60/cccccc/777.png">
                        <% end %>                        
                        
                    </div>
                    <div class="display-name">
                        <%= message.from.display_name %>
                        
                    </div>
               </div>
                <% if speaker == 'you' %>
                <div class="message-body">
                      <%= message.body%>
                      <div class="message-meta">
                      <%= time_ago_in_words(message.created_at)+"前" %> 
                      </div>
                       <%= link_to message_path(message), method: :delete, :class => 'btn btn-danger delete-btn btn-xs' do %>
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                       <% end %>
                </div>
                <% end %>              
                
            </li>
        <% end %>            
            
        </ul>
    <%= paginate @messages %>
    </div>
    <div class="row">
    <%= form_with model: @message,url:{controller: :messages,action: :create}, local: true do |form| %>
     
      <%= form.hidden_field :from_id,value: current_user.profile.id %>
      <%= form.hidden_field :to_id,value: params[:id]%>
        <div class="form-group">
        <%= form.label :body,"メッセージ送信" %><br>
        <%= form.text_area :body, class: "form-control" %>
        </div>       
         <%= form.submit class: "btn btn-default" %>
    <% end %>        
    </div>
</div>
</div>
<script>
 $(function(){
    $(".you .message-body").hover(function(){
        $(this).find(".delete-btn").fadeIn();
    },function(){
     $(this).find(".delete-btn").fadeOut();
    })
    ;
});   
</script>