config/routes.rb
Rails.application.routes.draw do
  
  get 'monologs/index'

  get 'monologs/show'

  get 'monologs/edit'

  get 'monologs/new'

  get 'cover_images/index'

  get 'cover_images/show'

  get 'cover_images/profile'

  # get 'messages/user/:id' =>'messages#user'
  
  # get 'messages/new' => 'messages#new'
  
  # post 'messages' => 'messages#create'
  # delete 'messages' => 'messages#destroy'
  
resources :profiles
resources :messages do 
  collection do
    get 'profile/:id' => 'messages#profile'
  end
end

resources :cover_images do 
  collection do
    get 'profile/:id' => 'cover_images#profile'
  end
end
  devise_for :users
  get 'pages/top'
  root 'pages#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 post 'relations/create' => 'relations#create'
 post 'relations/destroy' => 'relations#destroy_ajax'
 delete 'relations/:id' => 'relation#destroy'
 
 resources :monologs
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'MatchingSite',root_path,:class=>'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
         
          <li>
            <a href="#">
            <span class="glyphicon glyphicon-globe" aria-hidden="true"></span>
            </a>
            </li>
            <li>
            <a href="#">
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
            </a>
            </li>            
            
        
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
              <span class="caret"></span>
              </a>
            <ul class="dropdown-menu">
              <% if get_user_profile_id != nil %>
              <li><%=  link_to "プロフィールを編集", edit_profile_path(get_user_profile_id) %></li>
              <% else %>
              <li><%=  link_to "プロフィールを作成", new_profile_path(get_user_profile_id) %></li>
              <% end %>
              <li><%= link_to "設定変更", edit_user_registration_path %></li>

              <li role="separator" class="divider"></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>        
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse --> 
 
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sidebar.html.erb
 <div id="side-wrap">
     <% if current_user.profile != nil %>
        <aside id="your-profile" class="side-item">
            <div class="cover">
                
                <% if  current_user.profile.echo_main_cover %>
                <%= image_tag current_user.profile.echo_main_cover.url(:medium),:class => 'cover-img'%>
                <% else %>
                <img src=" https://dummyimage.com/260x110/cccccc/777.png" class="cover-img">
                <% end %>
            </div>
            <div class="your-info clearfix">
                 <div class="user_icon">
                    <% if  current_user.profile.echo_user_icon %>
                    <%= image_tag current_user.profile.echo_user_icon.url(:square),:width =>60,:height=>60%>
                    <% else %>
                    <img src=" https://dummyimage.com/60x60/cccccc/777.png">
                    <% end %>
                </div>                 
                 <div class="your-name">
                    <p class="display_name">
                        <%= current_user.profile.display_name %><br>
                        <small class="email">
                             <%= current_user.email %>
                        </small>
                    </p>
                </div>
            </div>
     

        <%= link_to "写真を追加する",'/cover_images/new', class: "btn btn-success btn-small"%>
        
        <div class="monologue">
            <%= form_with model: Profile.find(current_user.profile.id), local: true,:multipart => true do |form| %>
             <%= form.label :catch_copy ,"近況を一言" %><br>
            <%= form.text_area:catch_copy, class: "form-control monologue-text",:rows=>3,:placeholder=>'近況を一言' %>
            <%= form.submit class: "btn btn-default" %>
            <% end %>
        </div>
</aside>
<aside id="from-good" class="side-item">
    <p class="heading">マッチング成立中</p>
    <ul class="match-items">
    <% cnt = 0 %>
    <% current_user.profile.target_relation.each do |relation| %>
    <% prof = Profile.find(relation.profile_id) %>
    <% if relation.status == "good" && prof.self_relation_status(current_user.profile.id) == "good" %>
       <li class="match-item clearfix">
      <div class="profile-icon">
                <% if  prof.echo_user_icon %>
                <%= image_tag prof.echo_user_icon.url(:square),:width =>40,:height=>40%>
                <% else %>
                <img src=" https://dummyimage.com/60x60/cccccc/777.png">
                <% end %> 
      </div>  
      <p class="display_name">
          <%= prof.display_name %>
      </p>
          <%= link_to "メッセージ",'/messages/profile/' + prof.id.to_s , class: "btn btn-success btn-xs"%>
      </li>
      <% cnt += 1 %>
      <% end %>
    <% end %>
    <% if cnt == 0 %>
    <li>マッチング成立中の相手はいません</li>
    <% end %>
    </ul>    
</aside>
<aside id="from-good" class="side-item">
    <p class="heading">あなたにGood</p>
    <ul class="match-items">
    <% if current_user.profile.target_relation.size > 0 %>  
    <% current_user.profile.target_relation.each do |relation| %>
    <% prof = Profile.find(relation.profile_id) %>
    <% if relation.status == "good" && prof.self_relation_status(current_user.profile.id) != "good" && prof.self_relation_status(current_user.profile.id) != "skip"%>
    
    <li class="match-item clearfix">
        <div class="info clearfix">
            <div class="profile-icon">
                <% if  prof.echo_user_icon %>
                <%= image_tag prof.echo_user_icon.url(:square),:width =>40,:height=>40%>
                <% else %>
                <img src=" https://dummyimage.com/60x60/cccccc/777.png">
                <% end %>                   
                
            </div>  
            <p class="display_name">
              <%= prof.display_name %>
            </p>
        </div>
       <div class="btn-group btn-group-justified" role="group" aria-label="...">
            <a href="#" class="btn btn-danger status-btn add-btn" role="button" data-src-id="<%= current_user.profile.id %>" data-target-id="<%= prof.id %>" data-status="good">Good!</a> 
            
            <a href="#" class="btn btn-primary status-btn add-btn" role="button" data-src-id="<%= current_user.profile.id %>" data-target-id="<%= prof.id %>" data-status="skip">Skip</a> 
        </div>  
      
      </li>
      <% end %>
    <% end %>
    <% else %>
    <li>あなたにgoodを押している相手はいません</li>
    <% end %>
    </ul>
</aside>

<aside id="to-good" class="side-item">
      <p class="heading">あなたがGood</p>
      <% if current_user.profile.relation.size > 0 %> 
    <ul class="match-items">
    <% current_user.profile.relation.order("created_at desc").each do |relation| %>
    <% prof = Profile.find(relation.target_profile_id) %>
    <% if relation.status == "good"  && prof.second_relation_status(current_user.profile.id) != "good" %>
       <li class="match-item clearfix">
       
      <div class="profile-icon">
                <% if  prof.echo_user_icon %>
                <%= image_tag prof.echo_user_icon.url(:square),:width =>40,:height=>40%>
                <% else %>
                <img src=" https://dummyimage.com/60x60/cccccc/777.png">
                <% end %> 
            
      </div>  
      <p class="display_name">
          <%= prof.display_name %>
      </p>
       
      </li>
    <% end %>
    <% end %>    
    <% else %>
    あなたがgoodを押している相手はいません
    <% end %>
    </ul>  

</aside>
<% end %>
</div>

app/views/layouts/_sidebar2.html.erb
 <div id="side-wrap">
     <% if current_user.profile != nil %>
        <aside id="your-profile" class="side-item">
            <div class="cover">
                
                <% if  current_user.profile.echo_main_cover %>
                <%= image_tag current_user.profile.echo_main_cover.url(:medium),:class => 'cover-img'%>
                <% else %>
                <img src=" https://dummyimage.com/260x110/cccccc/777.png" class="cover-img">
                <% end %>
            </div>
            <div class="your-info clearfix">
                 <div class="user_icon">
                    <% if  current_user.profile.echo_user_icon %>
                    <%= image_tag current_user.profile.echo_user_icon.url(:square),:width =>60,:height=>60%>
                    <% else %>
                    <img src=" https://dummyimage.com/60x60/cccccc/777.png">
                    <% end %>
                </div>                 
                 <div class="your-name">
                    <p class="display_name">
                        <%= current_user.profile.display_name %><br>
                        <small class="email">
                             <%= current_user.email %>
                        </small>
                    </p>
                </div>
            </div>
     

    
</aside>
<% end %>
</div>

app/views/layouts/_sidebar3.html.erb
 <div id="side-wrap">
     <% if current_user.profile != nil %>
        <aside id="your-profile" class="side-item">
            <div class="cover">
                
                <% if  current_user.profile.echo_main_cover %>
                <%= image_tag current_user.profile.echo_main_cover.url(:medium),:class => 'cover-img'%>
                <% else %>
                <img src=" https://dummyimage.com/260x110/cccccc/777.png" class="cover-img">
                <% end %>
            </div>
            <div class="your-info clearfix">
                 <div class="user_icon">
                    <% if  current_user.profile.echo_user_icon %>
                    <%= image_tag current_user.profile.echo_user_icon.url(:square),:width =>60,:height=>60%>
                    <% else %>
                    <img src=" https://dummyimage.com/60x60/cccccc/777.png">
                    <% end %>
                </div>                 
                 <div class="your-name">
                    <p class="display_name">
                        <%= current_user.profile.display_name %><br>
                        <small class="email">
                             <%= current_user.email %>
                        </small>
                    </p>
                </div>
            </div>
     

</aside>
<aside id="from-good" class="side-item">
    <p class="heading">マッチング成立中</p>
    <ul class="match-items">
    <% cnt = 0 %>
    <% current_user.profile.target_relation.each do |relation| %>
    <% prof = Profile.find(relation.profile_id) %>
    <% if relation.status == "good" && prof.self_relation_status(current_user.profile.id) == "good" %>
       <li class="match-item clearfix">
      <div class="profile-icon">
                <% if  prof.echo_user_icon %>
                <%= image_tag prof.echo_user_icon.url(:square),:width =>40,:height=>40%>
                <% else %>
                <img src=" https://dummyimage.com/60x60/cccccc/777.png">
                <% end %> 
      </div>  
      <p class="display_name">
          <%= prof.display_name %>
      </p>
          <%= link_to "メッセージ",'/messages/profile/' + prof.id.to_s , class: "btn btn-success btn-xs"%>
      </li>
      <% cnt += 1 %>
      <% end %>
    <% end %>
    <% if cnt == 0 %>
    <li>マッチング成立中の相手はいません</li>
    <% end %>
    </ul>    
</aside>


<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatchingSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%
    arr = ["profiles", "messages", "cover_images"]
    %>
    <% if arr.include?(controller.controller_name) %>
    <script>
    var add_url = "<%= url_for(controller: :relations,action: :create) %>";
    var remove_url = "<%= url_for(controller: :relations,action: :destroy_ajax) %>";
    var index_url = "<%= url_for(controller: :profiles,action: :index) %>";      
    </script>
    <% end %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    
    <% if notice.present? %>
    <div class="container">
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
    </div>
    <% end %>
    
    <% if alert.present? %>
    <div class="container">
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
    </div>
    <% end %>
    
    
    
    <div class="container">


    <%= yield %>      
    </div>
  </body>
</html>